name: Deploy and Compile

on:
    push:
        branches: ["main"]
    
    workflow_dispatch:

jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Testing DSC
              run: Get-DscResource